FROM jupyter/pyspark-notebook
RUN pip3 install scylla-driver pyyaml

USER root
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/f/fuse/fuse_2.9.7-1ubuntu1_amd64.deb
RUN apt update -y
RUN apt install -y fuse gcc make flex bison byacc git curl 
# Install SBT
RUN apt-get install apt-transport-https curl gnupg -yqq
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
RUN curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
RUN chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
RUN apt-get update
RUN apt-get install sbt