FROM jupyter/pyspark-notebook
RUN pip3 install scylla-driver pyyaml

USER root
RUN wget http://archive.ubuntu.com/ubuntu/pool/main/f/fuse/fuse_2.9.7-1ubuntu1_amd64.deb
RUN apt update -y
RUN apt install -y fuse gcc make flex bison byacc git curl 
# Install SBT
RUN \
	echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list \
	&& apt-get update -y \
	&& apt-get install -y sbt \
  && sbt sbtVersion